window.LESSONS = [
  {
    id: "les-2",
    title: "Lesson 2",
    subtitle: "Pronunciation, compound vowels, R/B/P/V/F",
    parts: [
      {
        id: "les2-review",
        title: "L2·P1",
        label: "Homework words",
        items: [
          { nl: "melk", en: "milk", type: "word" },
          { nl: "energie", en: "energy (stress: e-NER-gie)", type: "word" },
          { nl: "nummer", en: "number (Dutch u ≠ English 'you')", type: "word" },
          { nl: "spiegel", en: "mirror", type: "word" },
          { nl: "zomer", en: "summer (z = voiced /z/)", type: "word" },
          { nl: "deur", en: "door (eu = round lips)", type: "word" },
          { nl: "ogen", en: "eyes (long vowel)", type: "word" },
          { nl: "goed", en: "good (final d weakens)", type: "word" },
          { nl: "brood", en: "bread (oo = long vowel)", type: "word" },
          { nl: "jongen", en: "boy (ng sound at end)", type: "word" },
          { nl: "lezen", en: "to read (e, NOT ei – say 'lay-zen')", type: "word" }
        ]
      },
      {
        id: "les2-ie-vowels",
        title: "L2·P2",
        label: "ie / y=ij vowel",
        items: [
          { nl: "fiets", en: "bicycle (ie = long ee, lips flat)", type: "word" },
          { nl: "vier", en: "four", type: "word" },
          { nl: "hier", en: "here", type: "word" },
          { nl: "dieren", en: "animals", type: "word" },
          { nl: "bier", en: "beer", type: "word" },
          { nl: "kiezen", en: "to choose", type: "word" },
          { nl: "lied", en: "song", type: "word" },
          { nl: "ziel", en: "soul", type: "word" },
          { nl: "vis", en: "fish (★ short i – NOT ie!)", type: "word" },
          { nl: "vies", en: "dirty / gross (★ long ie)", type: "word" },
          { nl: "fits", en: "fit / in shape (★ short i)", type: "word" },
          { nl: "eten", en: "to eat (first e = long)", type: "word" },
          { nl: "Chinees eten", en: "Chinese food", type: "phrase" },
          { nl: "Ik ben Chinees.", en: "I am Chinese.", type: "sentence" },
          { nl: "Ik spreek Chinees.", en: "I speak Chinese.", type: "sentence" }
        ]
      },
      {
        id: "les2-oe-eu",
        title: "L2·P3",
        label: "Vowels oe & eu",
        items: [
          { nl: "boek", en: "book (oe ≈ 'oo' as in pool)", type: "word" },
          { nl: "moeder", en: "mother", type: "word" },
          { nl: "voet", en: "foot", type: "word" },
          { nl: "koe", en: "cow", type: "word" },
          { nl: "snoep", en: "sweets / candy", type: "word" },
          { nl: "broek", en: "trousers / pants", type: "word" },
          { nl: "zoeken", en: "to look for", type: "word" },
          { nl: "bloem", en: "flower", type: "word" },
          { nl: "hoed", en: "hat", type: "word" },
          { nl: "stoel", en: "chair", type: "word" },
          { nl: "koel", en: "cool (temperature)", type: "word" },
          { nl: "koemelk", en: "cow's milk", type: "word" },
          { nl: "havermelk", en: "oat milk", type: "word" },
          { nl: "neus", en: "nose (★ eu = start flat, round lips)", type: "word" },
          { nl: "leuk", en: "nice / fun / cool (vs. mooi = beautiful)", type: "word" },
          { nl: "keuken", en: "kitchen", type: "word" },
          { nl: "kleur", en: "colour", type: "word" },
          { nl: "keurig", en: "neat / tidy", type: "word" }
        ]
      },
      {
        id: "les2-ui-ij-au",
        title: "L2·P4",
        label: "Vowels ui, ei/ij, au/ou",
        items: [
          { nl: "huis", en: "house / home (★ ui = A→U, big mouth change)", type: "word" },
          { nl: "uit", en: "out", type: "word" },
          { nl: "bruin", en: "brown", type: "word" },
          { nl: "fruit", en: "fruit", type: "word" },
          { nl: "tuin", en: "garden", type: "word" },
          { nl: "suiker", en: "sugar", type: "word" },
          { nl: "luisteren", en: "to listen", type: "word" },
          { nl: "lui", en: "lazy", type: "word" },
          { nl: "muis", en: "mouse", type: "word" },
          { nl: "Ik ben lui.", en: "I am lazy.", type: "sentence" },
          { nl: "mijn", en: "my (★ ei and ij sound the same!)", type: "word" },
          { nl: "klein", en: "small", type: "word" },
          { nl: "prijs", en: "price", type: "word" },
          { nl: "blijven", en: "to stay", type: "word" },
          { nl: "meisje", en: "girl", type: "word" },
          { nl: "tijd", en: "time", type: "word" },
          { nl: "kijken", en: "to look / to watch", type: "word" },
          { nl: "ijsje", en: "ice cream (ij = same as ei)", type: "word" },
          { nl: "konijn", en: "rabbit", type: "word" },
          { nl: "auto", en: "car (au ≈ 'ow' as in cow)", type: "word" },
          { nl: "blauw", en: "blue", type: "word" },
          { nl: "oud", en: "old", type: "word" },
          { nl: "fout", en: "mistake / wrong", type: "word" },
          { nl: "hout", en: "wood", type: "word" },
          { nl: "koud", en: "cold", type: "word" },
          { nl: "vrouw", en: "woman / wife", type: "word" },
          { nl: "goud", en: "gold", type: "word" },
          { nl: "pauze", en: "break / pause", type: "word" },
          { nl: "mooi", en: "beautiful / pretty (ooi = oo + ee)", type: "word" },
          { nl: "moeilijk", en: "difficult (oei = oo + ee)", type: "word" }
        ]
      },
      {
        id: "les2-consonants",
        title: "L2·P5",
        label: "R, B, P words",
        items: [
          { nl: "rood", en: "red", type: "word" },
          { nl: "rijst", en: "rice", type: "word" },
          { nl: "regen", en: "rain", type: "word" },
          { nl: "raam", en: "window", type: "word" },
          { nl: "rok", en: "skirt", type: "word" },
          { nl: "rug", en: "back (body part)", type: "word" },
          { nl: "rechts", en: "right (direction)", type: "word" },
          { nl: "reis", en: "journey / trip", type: "word" },
          { nl: "groen", en: "green", type: "word" },
          { nl: "groot", en: "big / large", type: "word" },
          { nl: "straat", en: "street", type: "word" },
          { nl: "trein", en: "train", type: "word" },
          { nl: "vragen", en: "to ask", type: "word" },
          { nl: "daar", en: "there", type: "word" },
          { nl: "maar", en: "but", type: "word" },
          { nl: "voor", en: "for / in front of", type: "word" },
          { nl: "leraar", en: "teacher", type: "word" },
          { nl: "baan", en: "job / lane", type: "word" },
          { nl: "been", en: "leg", type: "word" },
          { nl: "boom", en: "tree", type: "word" },
          { nl: "buik", en: "belly", type: "word" },
          { nl: "boterham", en: "sandwich / bread slice", type: "word" },
          { nl: "pas", en: "ID card / pass (★ p = no voice, air burst)", type: "word" },
          { nl: "pinpas", en: "bank card / debit card", type: "word" },
          { nl: "poes", en: "cat", type: "word" },
          { nl: "paard", en: "horse", type: "word" },
          { nl: "hulp", en: "help", type: "word" },
          { nl: "Ik heb een auto.", en: "I have a car. (heb – b at word end sounds like p)", type: "sentence" }
        ]
      }
    ]
  },
  {
    id: "les-3",
    title: "Lesson 3",
    subtitle: "Reading, ch/sch sounds, numbers 0–100, daily info",
    parts: [
      {
        id: "les3-vos",
        title: "L3·P1",
        label: "The vos story",
        items: [
          { nl: "vos", en: "fox", type: "word" },
          { nl: "bos", en: "forest", type: "word" },
          { nl: "mos", en: "moss", type: "word" },
          { nl: "hol", en: "burrow / hole", type: "word" },
          { nl: "tor", en: "beetle", type: "word" },
          { nl: "mal", en: "funny / strange / silly", type: "word" },
          { nl: "weg", en: "gone / away (also: road)", type: "word" },
          { nl: "Dit is vos.", en: "This is the fox.", type: "sentence" },
          { nl: "Vos is in het bos.", en: "The fox is in the forest.", type: "sentence" },
          { nl: "Het mos is groen.", en: "The moss is green.", type: "sentence" },
          { nl: "Vos is bij zijn huis.", en: "The fox is near its home.", type: "sentence" },
          { nl: "Zijn huis is een hol.", en: "Its home is a burrow.", type: "sentence" },
          { nl: "Wat is dat, vos?", en: "What is that, fox?", type: "question" },
          { nl: "Op je rug?", en: "On your back?", type: "question" },
          { nl: "Een tor!", en: "A beetle!", type: "sentence" },
          { nl: "Dat is mal.", en: "That is funny / strange.", type: "sentence" },
          { nl: "Dan is de tor weg.", en: "Then the beetle is gone.", type: "sentence" },
          { nl: "Hij zit op het mos.", en: "It sits on the moss.", type: "sentence" }
        ]
      },
      {
        id: "les3-ch-sch",
        title: "L3·P2",
        label: "ch, sch sounds & vocabulary",
        items: [
          { nl: "lachen", en: "to laugh (★ ch = throaty /x/, NOT English 'ch')", type: "word" },
          { nl: "licht", en: "light / bright", type: "word" },
          { nl: "acht", en: "eight (8) – ch is a throat sound", type: "word" },
          { nl: "nacht", en: "night", type: "word" },
          { nl: "school", en: "school (★ sch = s + throat sound, NOT 'sh')", type: "word" },
          { nl: "schoenen", en: "shoes", type: "word" },
          { nl: "schrijven", en: "to write", type: "word" },
          { nl: "schilderij", en: "painting", type: "word" },
          { nl: "schip", en: "ship", type: "word" },
          { nl: "Schiphol", en: "Amsterdam Airport Schiphol", type: "word" },
          { nl: "kaas", en: "cheese", type: "word" },
          { nl: "naam", en: "name (★ aa = long open A)", type: "word" },
          { nl: "maan", en: "moon", type: "word" },
          { nl: "banaan", en: "banana", type: "word" },
          { nl: "boot", en: "boat", type: "word" },
          { nl: "boete", en: "fine / penalty", type: "word" },
          { nl: "doos", en: "box", type: "word" },
          { nl: "klok", en: "clock", type: "word" },
          { nl: "kok", en: "cook / chef", type: "word" },
          { nl: "mok", en: "mug", type: "word" }
        ]
      },
      {
        id: "les3-numbers-0-20",
        title: "L3·P3",
        label: "Numbers 0–20",
        items: [
          { nl: "nul", en: "zero (0)", type: "word" },
          { nl: "een", en: "one (1); also: a / an", type: "word" },
          { nl: "twee", en: "two (2)", type: "word" },
          { nl: "drie", en: "three (3)", type: "word" },
          { nl: "vier", en: "four (4)", type: "word" },
          { nl: "vijf", en: "five (5) – ij is a diphthong", type: "word" },
          { nl: "zes", en: "six (6)", type: "word" },
          { nl: "zeven", en: "seven (7)", type: "word" },
          { nl: "acht", en: "eight (8) – ch = throaty sound", type: "word" },
          { nl: "negen", en: "nine (9)", type: "word" },
          { nl: "tien", en: "ten (10)", type: "word" },
          { nl: "elf", en: "eleven (11) – ★ irregular!", type: "word" },
          { nl: "twaalf", en: "twelve (12) – ★ irregular!", type: "word" },
          { nl: "dertien", en: "thirteen (13)", type: "word" },
          { nl: "veertien", en: "fourteen (14)", type: "word" },
          { nl: "vijftien", en: "fifteen (15)", type: "word" },
          { nl: "zestien", en: "sixteen (16)", type: "word" },
          { nl: "zeventien", en: "seventeen (17)", type: "word" },
          { nl: "achttien", en: "eighteen (18) – note double tt", type: "word" },
          { nl: "negentien", en: "nineteen (19)", type: "word" },
          { nl: "twintig", en: "twenty (20)", type: "word" },
          { nl: "en", en: "and (★ ≠ een = one!)", type: "word" }
        ]
      },
      {
        id: "les3-numbers-20-100",
        title: "L3·P4",
        label: "Numbers 20–100",
        items: [
          { nl: "dertig", en: "thirty (30)", type: "word" },
          { nl: "veertig", en: "forty (40) – ★ NOT viertig!", type: "word" },
          { nl: "vijftig", en: "fifty (50)", type: "word" },
          { nl: "zestig", en: "sixty (60)", type: "word" },
          { nl: "zeventig", en: "seventy (70)", type: "word" },
          { nl: "tachtig", en: "eighty (80) – ★ NOT achtig!", type: "word" },
          { nl: "negentig", en: "ninety (90)", type: "word" },
          { nl: "honderd", en: "one hundred (100)", type: "word" },
          { nl: "duizend", en: "one thousand (1,000)", type: "word" },
          { nl: "achtentwintig", en: "twenty-eight (28) – ★ units first: 8 + and + 20", type: "word" },
          { nl: "zevenendertig", en: "thirty-seven (37) – units first!", type: "word" },
          { nl: "drieënvijftig", en: "fifty-three (53)", type: "word" },
          { nl: "zesentwintig", en: "twenty-six (26)", type: "word" },
          { nl: "eenentachtig", en: "eighty-one (81)", type: "word" },
          { nl: "drieënnegentig", en: "ninety-three (93)", type: "word" },
          { nl: "honderdvier", en: "one hundred and four (104)", type: "word" },
          { nl: "Hoe lees je dit?", en: "How do you read this?", type: "question" }
        ]
      },
      {
        id: "les3-daily-questions",
        title: "L3·P5",
        label: "Daily questions & answers",
        items: [
          { nl: "Hoe oud ben je?", en: "How old are you?", type: "question" },
          { nl: "Ik ben dertig jaar oud.", en: "I am thirty years old.", type: "sentence" },
          { nl: "Hoeveel kost het?", en: "How much does it cost?", type: "question" },
          { nl: "Het kost negentien euro.", en: "It costs nineteen euros.", type: "sentence" },
          { nl: "Hoeveel kost deze?", en: "How much does this one cost?", type: "question" },
          { nl: "Hoeveel kost die?", en: "How much does that one cost?", type: "question" },
          { nl: "deze", en: "this one (near the speaker)", type: "word" },
          { nl: "die", en: "that one (away from speaker)", type: "word" },
          { nl: "Wat is je huisnummer?", en: "What is your house number?", type: "question" },
          { nl: "Mijn huisnummer is 237.", en: "My house number is 237.", type: "sentence" },
          { nl: "Wat is je postcode?", en: "What is your postal code?", type: "question" },
          { nl: "Mijn postcode is 3011 AB.", en: "My postal code is 3011 AB.", type: "sentence" },
          { nl: "Wat is je telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Mijn telefoonnummer is 06-56-78-09-23.", en: "My phone number is 06-56-78-09-23.", type: "sentence" },
          { nl: "Wat is je geboortedatum?", en: "What is your date of birth?", type: "question" },
          { nl: "Mijn geboortedatum is 19-05-2005.", en: "My date of birth is 19 May 2005.", type: "sentence" },
          { nl: "BRP", en: "Basisregistratie Personen – Dutch municipal register", type: "word" },
          { nl: "BSN", en: "Burgerservicenummer – Dutch citizen service number", type: "word" },
          { nl: "DigiD", en: "Digital Identity – Dutch government login", type: "word" }
        ]
      }
    ]
  },
  {
    id: "les-4a",
    title: "Lesson 4A",
    subtitle: "Numbers in context, money, fractions, front desk",
    parts: [
      {
        id: "les4a-two-digit",
        title: "L4A·P1",
        label: "Two-digit numbers",
        items: [
          { nl: "elf", en: "eleven (11) – irregular", type: "word" },
          { nl: "achttien", en: "eighteen (18) – double tt", type: "word" },
          { nl: "drieënvijftig", en: "fifty-three (53) – ★ units first: 3 + and + 50", type: "word" },
          { nl: "achtenzeventig", en: "seventy-eight (78)", type: "word" },
          { nl: "achtentwintig", en: "twenty-eight (28)", type: "word" },
          { nl: "zesenvijftig", en: "fifty-six (56)", type: "word" },
          { nl: "zesentwintig", en: "twenty-six (26)", type: "word" },
          { nl: "zevenendertig", en: "thirty-seven (37)", type: "word" },
          { nl: "eenentachtig", en: "eighty-one (81)", type: "word" },
          { nl: "drieënnegentig", en: "ninety-three (93)", type: "word" },
          { nl: "Hoe lees je dit?", en: "How do you read this?", type: "question" }
        ]
      },
      {
        id: "les4a-large-fractions",
        title: "L4A·P2",
        label: "Large numbers & fractions",
        items: [
          { nl: "honderd", en: "hundred (100)", type: "word" },
          { nl: "duizend", en: "thousand (1,000)", type: "word" },
          { nl: "tienduizend", en: "ten thousand (10,000)", type: "word" },
          { nl: "honderdduizend", en: "hundred thousand (100,000)", type: "word" },
          { nl: "een ton", en: "a hundred thousand – ★ colloquial slang for 100,000", type: "phrase" },
          { nl: "een miljoen", en: "one million (1,000,000)", type: "phrase" },
          { nl: "een miljard", en: "one billion (1,000,000,000)", type: "phrase" },
          { nl: "een half", en: "a half / one half (0.5)", type: "phrase" },
          { nl: "anderhalf", en: "one and a half (1.5)", type: "word" },
          { nl: "een kwart", en: "a quarter (¼); also: a quarter hour", type: "phrase" },
          { nl: "Ik wil een half brood.", en: "I want half a loaf of bread.", type: "sentence" },
          { nl: "Ik heb anderhalf uur gewacht.", en: "I waited for an hour and a half.", type: "sentence" },
          { nl: "Een kwartier is vijftien minuten.", en: "A quarter of an hour is fifteen minutes.", type: "sentence" },
          { nl: "Dat huis kost vijf ton.", en: "That house costs five hundred thousand.", type: "sentence" }
        ]
      },
      {
        id: "les4a-money",
        title: "L4A·P3",
        label: "Money, decimals & years",
        items: [
          { nl: "komma", en: "decimal comma (★ Europeans write 3,25 not 3.25)", type: "word" },
          { nl: "nul komma twee", en: "zero point two (0,2)", type: "phrase" },
          { nl: "drie komma vijfentwintig", en: "three point twenty-five (3,25)", type: "phrase" },
          { nl: "vijftien euro dertig", en: "fifteen euros thirty (€15,30)", type: "phrase" },
          { nl: "achtentwintig euro zesenvijftig", en: "twenty-eight euros fifty-six (€28,56)", type: "phrase" },
          { nl: "negenennegentig cent", en: "ninety-nine cents (€0,99)", type: "phrase" },
          { nl: "twintig cent", en: "twenty cents (€0,20)", type: "phrase" },
          { nl: "elfhonderd euro", en: "eleven hundred euros (€1,100) – like 'eleven hundred' in English", type: "phrase" },
          { nl: "negentien vierendertig", en: "year 1934 – split as 19 + 34", type: "phrase" },
          { nl: "tweeduizend twintig", en: "year 2020 – two thousand twenty", type: "phrase" },
          { nl: "zeventien drieëntachtig", en: "year 1783 – split as 17 + 83", type: "phrase" }
        ]
      },
      {
        id: "les4a-balie",
        title: "L4A·P4",
        label: "At the front desk",
        items: [
          { nl: "de balie", en: "the front desk / counter", type: "word" },
          { nl: "de medewerker", en: "the staff member / employee", type: "word" },
          { nl: "vragen stellen", en: "to ask questions", type: "phrase" },
          { nl: "antwoord geven", en: "to give an answer", type: "phrase" },
          { nl: "Goedemorgen.", en: "Good morning.", type: "sentence" },
          { nl: "Hoe gaat het?", en: "How are you? / How is it going?", type: "question" },
          { nl: "Goed, en met jou?", en: "Good, and you?", type: "sentence" },
          { nl: "Het gaat goed met mij.", en: "I am doing well.", type: "sentence" },
          { nl: "Dank je wel.", en: "Thank you.", type: "sentence" },
          { nl: "Graag gedaan.", en: "You're welcome.", type: "sentence" },
          { nl: "jouw", en: "your (★ emphatic – stronger than je)", type: "word" },
          { nl: "mijn", en: "my", type: "word" },
          { nl: "Hoe oud ben je?", en: "How old are you?", type: "question" },
          { nl: "Ik ben ... jaar oud.", en: "I am ... years old.", type: "sentence" },
          { nl: "Wat is jouw geboortedatum?", en: "What is your date of birth?", type: "question" },
          { nl: "Mijn geboortedatum is ...", en: "My date of birth is ...", type: "sentence" },
          { nl: "Wat is jouw telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Mijn telefoonnummer is ...", en: "My phone number is ...", type: "sentence" },
          { nl: "Wat is jouw huisnummer?", en: "What is your house number?", type: "question" },
          { nl: "Mijn huisnummer is ...", en: "My house number is ...", type: "sentence" },
          { nl: "Wat is jouw postcode?", en: "What is your postal code?", type: "question" },
          { nl: "Mijn postcode is ...", en: "My postal code is ...", type: "sentence" }
        ]
      }
    ]
  },
  {
    id: "les-4b",
    title: "Lesson 4B",
    subtitle: "Questions, dates, time, days, months, travel",
    parts: [
      {
        id: "personal-info",
        title: "L4B·P1",
        label: "Personal information",
        items: [
          { nl: "Hoe oud ben je?", en: "How old are you?", type: "question" },
          { nl: "Wat is jouw geboortedatum?", en: "What is your date of birth?", type: "question" },
          { nl: "Wat is je telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Wat is jouw telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Wat is je huisnummer?", en: "What is your house number?", type: "question" },
          { nl: "Wat is je postcode?", en: "What is your postal code?", type: "question" },
          { nl: "Ik ben achtentwintig jaar oud.", en: "I am twenty-eight years old.", type: "sentence" }
        ]
      },
      {
        id: "ordinal-numbers",
        title: "L4B·P2",
        label: "Ordinal numbers",
        items: [
          { nl: "de hoeveelste?", en: "Which number in order?", type: "phrase" },
          { nl: "eerste", en: "first", type: "word" },
          { nl: "tweede", en: "second", type: "word" },
          { nl: "derde", en: "third", type: "word" },
          { nl: "vierde", en: "fourth", type: "word" },
          { nl: "vijfde", en: "fifth", type: "word" },
          { nl: "zesde", en: "sixth", type: "word" },
          { nl: "zevende", en: "seventh", type: "word" },
          { nl: "achtste", en: "eighth", type: "word" },
          { nl: "negende", en: "ninth", type: "word" },
          { nl: "tiende", en: "tenth", type: "word" },
          { nl: "twintigste", en: "twentieth", type: "word" },
          { nl: "dertigste", en: "thirtieth", type: "word" },
          { nl: "honderdste", en: "hundredth", type: "word" },
          { nl: "duizendste", en: "thousandth", type: "word" },
          { nl: "Vandaag is de eerste september.", en: "Today is the first of September.", type: "sentence" },
          { nl: "Hij is de derde student.", en: "He is the third student.", type: "sentence" },
          { nl: "Ik woon op de vierde verdieping.", en: "I live on the fourth floor.", type: "sentence" },
          { nl: "Op welke verdieping woon je?", en: "Which floor do you live on?", type: "question" },
          { nl: "Zij werd tweede in de wedstrijd.", en: "She came second in the competition.", type: "sentence" }
        ]
      },
      {
        id: "days-months-seasons",
        title: "L4B·P3",
        label: "Days, months, seasons",
        items: [
          { nl: "maandag", en: "Monday", type: "word" },
          { nl: "dinsdag", en: "Tuesday", type: "word" },
          { nl: "woensdag", en: "Wednesday", type: "word" },
          { nl: "donderdag", en: "Thursday", type: "word" },
          { nl: "vrijdag", en: "Friday", type: "word" },
          { nl: "zaterdag", en: "Saturday", type: "word" },
          { nl: "zondag", en: "Sunday", type: "word" },
          { nl: "Welke dag is het vandaag?", en: "What day is it today?", type: "question" },
          { nl: "Het is vrijdag.", en: "It is Friday.", type: "sentence" },
          { nl: "Het is op dinsdag.", en: "It is on Tuesday.", type: "sentence" },
          { nl: "Ik werk op maandag.", en: "I work on Monday.", type: "sentence" },
          { nl: "in het weekend", en: "on the weekend", type: "phrase" },
          { nl: "Wij zijn vrij in het weekend.", en: "We are free on the weekend.", type: "sentence" },
          { nl: "januari", en: "January", type: "word" },
          { nl: "februari", en: "February", type: "word" },
          { nl: "maart", en: "March", type: "word" },
          { nl: "april", en: "April", type: "word" },
          { nl: "mei", en: "May", type: "word" },
          { nl: "juni", en: "June", type: "word" },
          { nl: "juli", en: "July", type: "word" },
          { nl: "augustus", en: "August", type: "word" },
          { nl: "september", en: "September", type: "word" },
          { nl: "oktober", en: "October", type: "word" },
          { nl: "november", en: "November", type: "word" },
          { nl: "december", en: "December", type: "word" },
          { nl: "In januari is het koud.", en: "It is cold in January.", type: "sentence" },
          { nl: "In juni is het warm.", en: "It is warm in June.", type: "sentence" },
          { nl: "Ik ga op vakantie in augustus.", en: "I go on vacation in August.", type: "sentence" },
          { nl: "de lente", en: "spring", type: "word" },
          { nl: "de zomer", en: "summer", type: "word" },
          { nl: "de herfst", en: "autumn", type: "word" },
          { nl: "de winter", en: "winter", type: "word" },
          { nl: "Maart is een lentemaand.", en: "March is a spring month.", type: "sentence" },
          { nl: "In september begint de herfst.", en: "Autumn starts in September.", type: "sentence" }
        ]
      },
      {
        id: "time",
        title: "L4B·P4",
        label: "Time expressions",
        items: [
          { nl: "seconde", en: "second", type: "word" },
          { nl: "minuut", en: "minute", type: "word" },
          { nl: "kwartier", en: "quarter hour", type: "word" },
          { nl: "uur", en: "hour; o'clock", type: "word" },
          { nl: "dag", en: "day", type: "word" },
          { nl: "week", en: "week", type: "word" },
          { nl: "maand", en: "month", type: "word" },
          { nl: "seizoen", en: "season", type: "word" },
          { nl: "jaar", en: "year", type: "word" },
          { nl: "eeuw", en: "century", type: "word" },
          { nl: "Hoe laat is het?", en: "What time is it?", type: "question" },
          { nl: "Het is twee uur.", en: "It is two o'clock.", type: "sentence" },
          { nl: "De les begint om negen uur.", en: "The lesson starts at nine o'clock.", type: "sentence" },
          { nl: "zes uur", en: "six o'clock", type: "phrase" },
          { nl: "vijf over zes", en: "five past six", type: "phrase" },
          { nl: "tien over zes", en: "ten past six", type: "phrase" },
          { nl: "kwart over zes", en: "quarter past six", type: "phrase" },
          { nl: "twintig over zes", en: "twenty past six", type: "phrase" },
          { nl: "vijf voor half zeven", en: "five before half past six", type: "phrase" },
          { nl: "half zeven", en: "half past six (★ 'half seven' means 6:30 in Dutch!)", type: "phrase" },
          { nl: "vijf over half zeven", en: "five after half past six (6:35)", type: "phrase" },
          { nl: "twintig voor zeven", en: "twenty to seven", type: "phrase" },
          { nl: "kwart voor zeven", en: "quarter to seven", type: "phrase" },
          { nl: "tien voor zeven", en: "ten to seven", type: "phrase" },
          { nl: "vijf voor zeven", en: "five to seven", type: "phrase" },
          { nl: "half drie", en: "half past two (2:30)", type: "phrase" },
          { nl: "half acht", en: "half past seven (7:30)", type: "phrase" },
          { nl: "half elf", en: "half past ten (10:30)", type: "phrase" },
          { nl: "half twaalf", en: "half past eleven (11:30)", type: "phrase" },
          { nl: "'s ochtends", en: "in the morning", type: "phrase" },
          { nl: "'s middags", en: "in the afternoon", type: "phrase" },
          { nl: "'s avonds", en: "in the evening", type: "phrase" },
          { nl: "'s nachts", en: "at night", type: "phrase" },
          { nl: "Het is acht uur 's ochtends.", en: "It is eight o'clock in the morning.", type: "sentence" },
          { nl: "Het is tien uur 's avonds.", en: "It is ten o'clock in the evening.", type: "sentence" }
        ]
      },
      {
        id: "travel",
        title: "L4B·P5",
        label: "Train and airport",
        items: [
          { nl: "Hoe laat vertrekt de trein naar Amsterdam?", en: "What time does the train to Amsterdam leave?", type: "question" },
          { nl: "Hoelang duurt de reis?", en: "How long does the journey take?", type: "question" },
          { nl: "Op welk spoor moet ik zijn?", en: "Which platform should I be on?", type: "question" },
          { nl: "De trein vertrekt om zeventien uur achtenveertig.", en: "The train leaves at 17:48.", type: "sentence" },
          { nl: "De reis duurt dertig minuten.", en: "The journey takes thirty minutes.", type: "sentence" },
          { nl: "de trein", en: "the train", type: "word" },
          { nl: "het station", en: "the station", type: "word" },
          { nl: "het spoor", en: "the platform; the track", type: "word" },
          { nl: "vertrek", en: "departure", type: "word" },
          { nl: "aankomst", en: "arrival", type: "word" },
          { nl: "enkele reis", en: "one-way ticket", type: "phrase" },
          { nl: "retour", en: "return ticket", type: "word" },
          { nl: "de reis", en: "the journey", type: "word" },
          { nl: "de luchthaven", en: "the airport", type: "word" },
          { nl: "de ingang", en: "the entrance", type: "word" },
          { nl: "de poort", en: "the gate", type: "word" },
          { nl: "gate", en: "gate", type: "word" },
          { nl: "de koffer", en: "the suitcase", type: "word" },
          { nl: "het restaurant", en: "the restaurant", type: "word" },
          { nl: "check-in", en: "check-in", type: "word" }
        ]
      }
    ]
  }
];
