window.LESSONS = [
  {
    id: "les-4b",
    title: "Lesson 4B",
    subtitle: "Questions, dates, time, days, months, travel",
    parts: [
      {
        id: "personal-info",
        title: "Part 1",
        label: "Personal information",
        items: [
          { nl: "Hoe oud ben je?", en: "How old are you?", type: "question" },
          { nl: "Wat is jouw geboortedatum?", en: "What is your date of birth?", type: "question" },
          { nl: "Wat is je telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Wat is jouw telefoonnummer?", en: "What is your phone number?", type: "question" },
          { nl: "Wat is je huisnummer?", en: "What is your house number?", type: "question" },
          { nl: "Wat is je postcode?", en: "What is your postal code?", type: "question" },
          { nl: "Ik ben achtentwintig jaar oud.", en: "I am twenty-eight years old.", type: "sentence" }
        ]
      },
      {
        id: "ordinal-numbers",
        title: "Part 2",
        label: "Ordinal numbers",
        items: [
          { nl: "de hoeveelste?", en: "Which number in order?", type: "phrase" },
          { nl: "eerste", en: "first", type: "word" },
          { nl: "tweede", en: "second", type: "word" },
          { nl: "derde", en: "third", type: "word" },
          { nl: "vierde", en: "fourth", type: "word" },
          { nl: "vijfde", en: "fifth", type: "word" },
          { nl: "zesde", en: "sixth", type: "word" },
          { nl: "zevende", en: "seventh", type: "word" },
          { nl: "achtste", en: "eighth", type: "word" },
          { nl: "negende", en: "ninth", type: "word" },
          { nl: "tiende", en: "tenth", type: "word" },
          { nl: "twintigste", en: "twentieth", type: "word" },
          { nl: "dertigste", en: "thirtieth", type: "word" },
          { nl: "honderdste", en: "hundredth", type: "word" },
          { nl: "duizendste", en: "thousandth", type: "word" },
          { nl: "Vandaag is de eerste september.", en: "Today is the first of September.", type: "sentence" },
          { nl: "Hij is de derde student.", en: "He is the third student.", type: "sentence" },
          { nl: "Ik woon op de vierde verdieping.", en: "I live on the fourth floor.", type: "sentence" },
          { nl: "Op welke verdieping woon je?", en: "Which floor do you live on?", type: "question" },
          { nl: "Zij werd tweede in de wedstrijd.", en: "She came second in the competition.", type: "sentence" }
        ]
      },
      {
        id: "days-months-seasons",
        title: "Part 3",
        label: "Days, months, seasons",
        items: [
          { nl: "maandag", en: "Monday", type: "word" },
          { nl: "dinsdag", en: "Tuesday", type: "word" },
          { nl: "woensdag", en: "Wednesday", type: "word" },
          { nl: "donderdag", en: "Thursday", type: "word" },
          { nl: "vrijdag", en: "Friday", type: "word" },
          { nl: "zaterdag", en: "Saturday", type: "word" },
          { nl: "zondag", en: "Sunday", type: "word" },
          { nl: "Welke dag is het vandaag?", en: "What day is it today?", type: "question" },
          { nl: "Het is vrijdag.", en: "It is Friday.", type: "sentence" },
          { nl: "Het is op dinsdag.", en: "It is on Tuesday.", type: "sentence" },
          { nl: "Ik werk op maandag.", en: "I work on Monday.", type: "sentence" },
          { nl: "in het weekend", en: "on the weekend", type: "phrase" },
          { nl: "Wij zijn vrij in het weekend.", en: "We are free on the weekend.", type: "sentence" },
          { nl: "januari", en: "January", type: "word" },
          { nl: "februari", en: "February", type: "word" },
          { nl: "maart", en: "March", type: "word" },
          { nl: "april", en: "April", type: "word" },
          { nl: "mei", en: "May", type: "word" },
          { nl: "juni", en: "June", type: "word" },
          { nl: "juli", en: "July", type: "word" },
          { nl: "augustus", en: "August", type: "word" },
          { nl: "september", en: "September", type: "word" },
          { nl: "oktober", en: "October", type: "word" },
          { nl: "november", en: "November", type: "word" },
          { nl: "december", en: "December", type: "word" },
          { nl: "In januari is het koud.", en: "It is cold in January.", type: "sentence" },
          { nl: "In juni is het warm.", en: "It is warm in June.", type: "sentence" },
          { nl: "Ik ga op vakantie in augustus.", en: "I go on vacation in August.", type: "sentence" },
          { nl: "de lente", en: "spring", type: "word" },
          { nl: "de zomer", en: "summer", type: "word" },
          { nl: "de herfst", en: "autumn", type: "word" },
          { nl: "de winter", en: "winter", type: "word" },
          { nl: "Maart is een lentemaand.", en: "March is a spring month.", type: "sentence" },
          { nl: "In september begint de herfst.", en: "Autumn starts in September.", type: "sentence" }
        ]
      },
      {
        id: "time",
        title: "Part 4",
        label: "Time expressions",
        items: [
          { nl: "seconde", en: "second", type: "word" },
          { nl: "minuut", en: "minute", type: "word" },
          { nl: "kwartier", en: "quarter hour", type: "word" },
          { nl: "uur", en: "hour; o'clock", type: "word" },
          { nl: "dag", en: "day", type: "word" },
          { nl: "week", en: "week", type: "word" },
          { nl: "maand", en: "month", type: "word" },
          { nl: "seizoen", en: "season", type: "word" },
          { nl: "jaar", en: "year", type: "word" },
          { nl: "eeuw", en: "century", type: "word" },
          { nl: "Hoe laat is het?", en: "What time is it?", type: "question" },
          { nl: "Het is twee uur.", en: "It is two o'clock.", type: "sentence" },
          { nl: "De les begint om negen uur.", en: "The lesson starts at nine o'clock.", type: "sentence" },
          { nl: "zes uur", en: "six o'clock", type: "phrase" },
          { nl: "vijf over zes", en: "five past six", type: "phrase" },
          { nl: "tien over zes", en: "ten past six", type: "phrase" },
          { nl: "kwart over zes", en: "quarter past six", type: "phrase" },
          { nl: "twintig over zes", en: "twenty past six", type: "phrase" },
          { nl: "vijf voor half zeven", en: "five before half past six", type: "phrase" },
          { nl: "half zeven", en: "half past six", type: "phrase" },
          { nl: "vijf over half zeven", en: "five after half past six", type: "phrase" },
          { nl: "twintig voor zeven", en: "twenty to seven", type: "phrase" },
          { nl: "kwart voor zeven", en: "quarter to seven", type: "phrase" },
          { nl: "tien voor zeven", en: "ten to seven", type: "phrase" },
          { nl: "vijf voor zeven", en: "five to seven", type: "phrase" },
          { nl: "zeven uur", en: "seven o'clock", type: "phrase" },
          { nl: "half drie", en: "half past two", type: "phrase" },
          { nl: "half acht", en: "half past seven", type: "phrase" },
          { nl: "half elf", en: "half past ten", type: "phrase" },
          { nl: "half twaalf", en: "half past eleven", type: "phrase" },
          { nl: "'s ochtends", en: "in the morning", type: "phrase" },
          { nl: "'s middags", en: "in the afternoon", type: "phrase" },
          { nl: "'s avonds", en: "in the evening", type: "phrase" },
          { nl: "'s nachts", en: "at night", type: "phrase" },
          { nl: "Het is acht uur 's ochtends.", en: "It is eight o'clock in the morning.", type: "sentence" },
          { nl: "Het is tien uur 's avonds.", en: "It is ten o'clock in the evening.", type: "sentence" }
        ]
      },
      {
        id: "travel",
        title: "Part 5",
        label: "Train and airport",
        items: [
          { nl: "Hoe laat vertrekt de trein naar Amsterdam?", en: "What time does the train to Amsterdam leave?", type: "question" },
          { nl: "Hoelang duurt de reis?", en: "How long does the journey take?", type: "question" },
          { nl: "Op welk spoor moet ik zijn?", en: "Which platform should I be on?", type: "question" },
          { nl: "De trein vertrekt om zeventien uur achtenveertig.", en: "The train leaves at 17:48.", type: "sentence" },
          { nl: "De reis duurt dertig minuten.", en: "The journey takes thirty minutes.", type: "sentence" },
          { nl: "de trein", en: "the train", type: "word" },
          { nl: "het station", en: "the station", type: "word" },
          { nl: "het spoor", en: "the platform; the track", type: "word" },
          { nl: "vertrek", en: "departure", type: "word" },
          { nl: "aankomst", en: "arrival", type: "word" },
          { nl: "enkele reis", en: "one-way ticket", type: "phrase" },
          { nl: "retour", en: "return ticket", type: "word" },
          { nl: "de reis", en: "the journey", type: "word" },
          { nl: "de luchthaven", en: "the airport", type: "word" },
          { nl: "de ingang", en: "the entrance", type: "word" },
          { nl: "de poort", en: "the gate", type: "word" },
          { nl: "gate", en: "gate", type: "word" },
          { nl: "de koffer", en: "the suitcase", type: "word" },
          { nl: "het restaurant", en: "the restaurant", type: "word" },
          { nl: "check-in", en: "check-in", type: "word" }
        ]
      }
    ]
  }
];
